version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      - "--noauth"
  api:
    image: paulohsampaio/api
    ports:
      - "3010:3010"
    links:
      - mongo