version: "3"
services:
  api:
    image: paulohsampaio/api
    ports:
      - "80:3010"
    links:
      - conexao
  conexao:
    image: mongo
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      - --noauth